# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import banking_pb2 as banking__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in banking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BankServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCustomer = channel.unary_unary(
                '/banking.v1.BankService/CreateCustomer',
                request_serializer=banking__pb2.CreateCustomerRequest.SerializeToString,
                response_deserializer=banking__pb2.CustomerResponse.FromString,
                _registered_method=True)
        self.CreateAccount = channel.unary_unary(
                '/banking.v1.BankService/CreateAccount',
                request_serializer=banking__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=banking__pb2.AccountResponse.FromString,
                _registered_method=True)
        self.Deposit = channel.unary_unary(
                '/banking.v1.BankService/Deposit',
                request_serializer=banking__pb2.DepositRequest.SerializeToString,
                response_deserializer=banking__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.Withdraw = channel.unary_unary(
                '/banking.v1.BankService/Withdraw',
                request_serializer=banking__pb2.WithdrawRequest.SerializeToString,
                response_deserializer=banking__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/banking.v1.BankService/GetBalance',
                request_serializer=banking__pb2.BalanceRequest.SerializeToString,
                response_deserializer=banking__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.CloseAccount = channel.unary_unary(
                '/banking.v1.BankService/CloseAccount',
                request_serializer=banking__pb2.CloseAccountRequest.SerializeToString,
                response_deserializer=banking__pb2.CloseAccountResponse.FromString,
                _registered_method=True)


class BankServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deposit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Withdraw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BankServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCustomer,
                    request_deserializer=banking__pb2.CreateCustomerRequest.FromString,
                    response_serializer=banking__pb2.CustomerResponse.SerializeToString,
            ),
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=banking__pb2.CreateAccountRequest.FromString,
                    response_serializer=banking__pb2.AccountResponse.SerializeToString,
            ),
            'Deposit': grpc.unary_unary_rpc_method_handler(
                    servicer.Deposit,
                    request_deserializer=banking__pb2.DepositRequest.FromString,
                    response_serializer=banking__pb2.TransactionResponse.SerializeToString,
            ),
            'Withdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.Withdraw,
                    request_deserializer=banking__pb2.WithdrawRequest.FromString,
                    response_serializer=banking__pb2.TransactionResponse.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=banking__pb2.BalanceRequest.FromString,
                    response_serializer=banking__pb2.BalanceResponse.SerializeToString,
            ),
            'CloseAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseAccount,
                    request_deserializer=banking__pb2.CloseAccountRequest.FromString,
                    response_serializer=banking__pb2.CloseAccountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'banking.v1.BankService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('banking.v1.BankService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BankService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.v1.BankService/CreateCustomer',
            banking__pb2.CreateCustomerRequest.SerializeToString,
            banking__pb2.CustomerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.v1.BankService/CreateAccount',
            banking__pb2.CreateAccountRequest.SerializeToString,
            banking__pb2.AccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.v1.BankService/Deposit',
            banking__pb2.DepositRequest.SerializeToString,
            banking__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Withdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.v1.BankService/Withdraw',
            banking__pb2.WithdrawRequest.SerializeToString,
            banking__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.v1.BankService/GetBalance',
            banking__pb2.BalanceRequest.SerializeToString,
            banking__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.v1.BankService/CloseAccount',
            banking__pb2.CloseAccountRequest.SerializeToString,
            banking__pb2.CloseAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
